site_name: Starlette Korean
site_description: 빛나는 작은 ASGI 프레임워크.
site_url: https://starlette.pinstella.com

theme:
  name: 'material'
  custom_dir: docs/overrides
  palette:
    - scheme: 'default'
      media: '(prefers-color-scheme: light)'
      toggle:
        icon: 'material/lightbulb'
        name: "Switch to dark mode"
    - scheme: 'slate'
      media: '(prefers-color-scheme: dark)'
      primary: 'blue'
      toggle:
        icon: 'material/lightbulb-outline'
        name: 'Switch to light mode'
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy

repo_name: encode/starlette
repo_url: https://github.com/encode/starlette
edit_uri: edit/master/docs/

nav:
  - 소개: 'index.md'
  - Applications: 'applications.md'
  - 요청: 'requests.md'
  - 응답: 'responses.md'
  - WebSockets: 'websockets.md'
  - 라우팅: 'routing.md'
  - Endpoints: 'endpoints.md'
  - Middleware: 'middleware.md'
  - 정적 파일: 'staticfiles.md'
  - 템플릿: 'templates.md'
  - Database: 'database.md'
  - GraphQL: 'graphql.md'
  - 인증: 'authentication.md'
  - API Schemas: 'schemas.md'
  - 수명: 'lifespan.md'
  - Background Tasks: 'background.md'
  - Server Push: 'server-push.md'
  - 예외: 'exceptions.md'
  - 구성: 'config.md'
  - Test Client: 'testclient.md'
  - Third Party Packages: 'third-party-packages.md'
  - 기여하기: 'contributing.md'
  - Release Notes: 'release-notes.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
